config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources 'provider_sales' do
    get 'find_coupon', on: :collection
    post 'apply_coupon', on: :collection
  end

  resources 'companies'
  resources 'businesses'
  devise_for 'users', controllers: { registrations: 'registrations' }

  root to: "home#index"

  resources 'dashboard' do
    get 'extend_profile_1', on: :collection
    patch 'update_profile', on: :collection
    get 'available_coupons', on: :collection
    post 'obtain_coupon', on: :collection
    get 'coupons_wallet', on: :collection
  end

  resources 'games', only: ['index', 'show', 'evaluate'] do
    post 'process_user_input', on: :collection
  end

  get 'user_root' => 'dashboard#index', as: 'user_root'
  get 'dashboard/extend_profile_1' => 'dashboard#extend_profile_1'
  patch 'dashboard/update_profile' => 'dashboard#update_profile'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  # before_action :load_and_authorize_resource

  def index
  end

  # NOTE: not in use right now
  def extend_profile_1
  end

  def update_profile
    current_user.update_attributes(profile_params)
    redirect_to action: :index
  end

  def available_coupons
    @coupons = ProviderCouponsDecorator
      .new(
        ProviderSale
          .all
          .order(id: 'desc')
          .where('available_stock > 0')
        )
      .decorate
  end

  def obtain_coupon
    coupon_obtainer = CouponObtainer.new(
      consumer: current_user,
      provider_coupon: ProviderSale.find(params[:coupon_id])
    )
    coupon_obtainer.perform

    if coupon_obtainer.successful?
      flash[:notice] = 'Cupón obtenido. El cupón ha sido agregado a tu cartera de cupones.'
      redirect_to action: :coupons_wallet
    else
      flash[:alert] = "Ha ocurrido un error. Intenta más tarde. Código(s) de error: #{coupon_obtainer.error_codes}"
      redirect_to action: :available_coupons
    end
  end

  def coupons_wallet
    @coupons = ConsumerCouponsDecorator
      .new(
        ConsumerCoupon.includes(:provider_coupon)
                      .where(user_id: current_user.id)
                      .order('id DESC')
      )
      .decorate


    if @coupons.length < 1
      flash[:alert] = 'No haz agregado ningún ticket a tu cartera aún. Juega y gana cupones!'
      redirect_to action: 'index'
    end
  end

  private

  def profile_params
    params
      .require('user')
      .permit(:avatar_id)
  end
end

app/views/dashboard/_dashboard_consumer.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'dashboard/dashboard_consumer', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-10 text-center">
      <figure id="foto-perfil">
        <img src="/images/dashboard-player/avatar.png" class="img-fluid">
      </figure>

      <div class="row">
        <div class="col-xs-2" id="monedas">
          <img src="/images/dashboard-player/monedas.png">
        </div>
        <div class="col-xs-2">
          <a href="" class="text-right d-block" id="score-monedas">
            <%= current_user.points_earned %>
          </a>
        </div>
      </div>

      <div class="flex-column d-flex mt-4">
        <span id="usuario-jugador"><%= current_user.full_name.split(' ').first(2).join(' ') %></span>

        <%= link_to coupons_wallet_dashboard_index_path, class: 'mt-3 btn btn-yellow', id: 'btn-nuevo-cupon' do %>
          <i class='fa fa-ticket-alt'></i>
          Mis cupones
        <% end %>

        <%= link_to 'Quiero jugar', games_path, class: 'mt-3 btn btn-success' %>

        <br />
        <br />
        <%= link_to 'Comprar cupones', available_coupons_dashboard_index_path, class: 'btn btn-yellow' %>
      </div>
    </div>
  </div>
  <br />
</div>

app/views/dashboard/_dashboard_provider.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'dashboard/dashboard_provider', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<!-- Page Content  -->
<div id="content" class='dashboard-provider'>
  <div class="container mt-10">
    <div class="row justify-content-center">
      <div class="col-12 text-center">
        <figure id="foto-perfil">
          <img src="/images/logo-perfil.png" class="img-fluid" width="180" style='width: 180px'>
        </figure>

        <div class="flex-column d-flex">
          <br />
          <br />
          <%= link_to 'Cupones Activos', provider_sales_path, class: 'btn btn-success' %>
          <%= link_to 'Nuevo Cupón', new_provider_sale_path, class: 'btn btn-yellow mt-3' %>
          <br />
          <br />
          <%= link_to 'Aplicar cupón', find_coupon_provider_sales_path, class: 'btn btn-yellow' %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/dashboard/available_coupons.html.erb
<div class='container'>
  <div class='row justify-content-center mt-1'>
    <% @coupons.each do |coupon| %>
      <%= render partial: 'provider_sales/coupon_card', locals: { coupon: coupon, render_style: 'for_consumer' } %>
    <% end %>
  </div>
</div>

app/views/dashboard/consumer_coupons.html.erb
<div class='container'>
  <div class='row justify-content-center mt-1'>
    <% @consumer_coupons.each do |consumer_coupon| %>
      <%= render partial: 'provider_sales/coupon_card', locals: { coupon: consumer_coupon  } %>
    <% end %>
  </div>
</div>

app/views/dashboard/coupons_wallet.html.erb
<div class="container" id='provider-sales-index'>
  <div class="row justify-content-center mt-1">
    <% @coupons.each do |coupon| %>
      <%= render partial: 'provider_sales/coupon_card', locals: { coupon: coupon, render_style: 'for_provider' } %>
    <% end %>
  </div>
</div>

app/views/dashboard/extend_profile_1.html.erb
<%= content_for :header do %>
  <%= stylesheet_link_tag 'dashboard/extend_profile_1', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="wrapper" id='extend_profile_1'>
  <!-- Page Content  -->
  <div id="content">

    <div class="container">

      <div class="row justify-content-center no-margin">
          <div class="col-md-8" id="registro">

              <div class="avatar" >

                  <div class="name-user" >
                      <div class="name">
                        <img class="pencil" src="/images/avatar/pencil.png">
                        <input type="text" class="form-control user-name-text-input" placeholder="Nombre de usuario">
                      </div>


                      <img class="rounded-circle" src="/images/avatar/Elipse 22.png" data-holder-rendered="true">
                      <img class="camera" src="/images/avatar/camera.png">
                      <img class="borde" src="/images/avatar/borde.png">

                  </div>


                  <div class="images">
                      <div class="row avatar-images-wrapper">
                          <div class="col-3 col-sm-3 avatar-select">
                              <img class='avatar-image' src="/images/avatar/avatar1.png">
                          </div>

                          <div class="col-3 col-sm-3 avatar-select">
                              <img class='avatar-image' src="/images/avatar/avatar3.png">
                          </div>

                          <div class="col-3 col-sm-3 avatar-select">
                              <img class='avatar-image' src="/images/avatar/avatar3.png">
                          </div>
                      </div>

                      <div class="row avatar-images-wrapper">
                          <div class="col-3 col-sm-3 avatar-select" >
                              <img class='avatar-image' src="/images/avatar/avatar4.png">
                          </div>

                          <div class="col-3 col-sm-3 avatar-select">
                              <img class='avatar-image' src="/images/avatar/avatar5.png">
                          </div>

                          <div class="col-3 col-sm-3 avatar-select">
                              <img class='avatar-image' src="/images/avatar/avatar6.png">
                          </div>
                      </div>
                  </div>


              </div>



                  <h4 id="intereses-h4">Intereses</h4>
                  <div class="row" id="intereses">

                      <div class="col-6 col-sm-3"><div class="form-check">
                          <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1" value="option1">
                          <label class="form-check-label" for="exampleRadios1">
                            Alimentos y bebidas
                          </label>
                        </div>
                      </div>

                      <div class="col-6 col-sm-3">
                          <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1" value="option1">
                              <label class="form-check-label" for="exampleRadios1">
                                Ropa
                              </label>
                          </div>
                      </div>

                      <div class="col-6 col-sm-3"><div class="form-check">
                          <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1" value="option1">
                          <label class="form-check-label" for="exampleRadios1">
                            Viajes y Ocio
                          </label>
                        </div>
                      </div>

                      <div class="col-6 col-sm-3">
                          <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1" value="option1">
                              <label class="form-check-label" for="exampleRadios1">
                                Abarrotes
                              </label>
                          </div>
                      </div>

                      <div class="col-6 col-sm-3"><div class="form-check">
                          <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1" value="option1">
                          <label class="form-check-label" for="exampleRadios1">
                            Productos Hogar
                          </label>
                        </div>
                      </div>

                      <div class="col-6 col-sm-3">
                          <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1" value="option1">
                              <label class="form-check-label" for="exampleRadios1">
                                Otros
                              </label>
                          </div>
                      </div>

                  </div>



                  <%= form_for(current_user, as: 'user', url: dashboard_update_profile_path) do |f| %>
                    <%= f.hidden_field :avatar_id, value: '1' %>
                    <div class="form-group text-right">
                        <button class="btn">
                            Guardar
                        </button>
                    </div>
                  <% end %>

          </div>
      </div>
      </div>
  </div>


</div>

app/views/dashboard/index.html.erb
<% if current_user.provider_role? %>
  <%= render partial: 'dashboard_provider' %>
<% elsif current_user.consumer_role? %>
  <%= render partial: 'dashboard_consumer' %>
<% end %>