config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources 'provider_sales' do
    get 'find_coupon', on: :collection
    post 'apply_coupon', on: :collection
  end

  resources 'companies'
  resources 'businesses'
  devise_for 'users', controllers: { registrations: 'registrations' }

  root to: "home#index"

  resources 'dashboard' do
    get 'extend_profile_1', on: :collection
    patch 'update_profile', on: :collection
    get 'available_coupons', on: :collection
    post 'obtain_coupon', on: :collection
    get 'coupons_wallet', on: :collection
  end

  resources 'games', only: ['index', 'show', 'evaluate'] do
    post 'process_user_input', on: :collection
  end

  get 'user_root' => 'dashboard#index', as: 'user_root'
  get 'dashboard/extend_profile_1' => 'dashboard#extend_profile_1'
  patch 'dashboard/update_profile' => 'dashboard#update_profile'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :yes_no_questions, foreign_key: 'game_id'

  has_one_attached :game_image
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.where(visible: true)
  end

  def show
    @game = Game.find(params[:id])
  end

  def process_user_input
    @game = Game.find(params[:id])
    @results = params[:yes_no_question_results]
      .keys
      .reduce({}) do |acc, yes_no_question_id|
        yes_no_question_result_answer = params[:yes_no_question_results][yes_no_question_id] == 'on'
        yes_no_question = YesNoQuestion.find(yes_no_question_id)

        acc[yes_no_question_id] = yes_no_question.is_true == yes_no_question_result_answer ? 'correct' : 'incorrect'
        acc
      end

    if @results.values.include?('incorrect')
      flash[:alert] = "Algunas de tus respuestas fueron incorrectas, intenta de nuevo!"
    else
      flash[:notice] = "Contestaste la trivia correctamente, haz ganado #{@game.points_offered} puntos!"

      current_user.update_attributes(
        points_earned: current_user.points_earned + @game.points_offered
      )
    end

    redirect_to game_path(id: @game.id)
  end
end

app/views/games/_game.html.erb
<div class="col align-self-center">
  <div class="d-flex justify-content-center">
    <div class="card mt-4" style="width: 20rem;">
      <img
        src='<%= game.game_image.try(:service_url) %>'
        class='card-img-top'
      >

      <div class="card-body">
        <h6 style="text-align: center; font-family: Arial, Helvetica, sans-serif; font-weight: bold;">
          <%= game.title %>
        </h6>

        <hr style="margin-top: 0px; height: 0.5px; background-color: black;" />

        <p style=" font-family: Arial, Helvetica, sans-serif">
          <%= game.description %>
        </p>

        <div class='button-canjear text-right'>
          <a
            data-toggle='modal'
            data-target='.modal-game-<%= game.id %>'
            class='btn btn-success'
            href='#'
          >
            Jugar
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class='modal modal-game-<%= game.id %>' tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content text-center">
      <div class="modal-header">
        <%= game.title %>
      </div>

      <div class="content">
        <div class="row text-left">
          <div class="col" style='font-size: 15px'>
            <%= game.summary %>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <div class='col text-right'>
          <a href='#' class='btn btn-default-no-background' data-dismiss='modal'>Salir</a>
          <%= link_to 'Jugar', game_path(id: game.id), class: 'btn btn-success' %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/games/_yes_no_question.html.erb
<div class="col align-self-center yes-no-question-container">
  <div class="d-flex justify-content-center">

    <div class="card mt-4" style="width: 20rem;">
      <img
        class='card-img-top'
        src='<%= yes_no_question.yes_no_question_image.try(:service_url) %>'
      />

      <div class="card-body">
        <p style=" font-family: Arial, Helvetica, sans-serif" id="question">
          <%= yes_no_question.title %>
        </p>

        <div class="row text-left">
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-success" for="<%= "#{yes_no_question.id}_true" %>">
              <input
                type="radio"
                name="yes_no_question_results[<%= yes_no_question.id %>]"
                id="<%= "#{yes_no_question.id}_true" %>"
                autocomplete="off"
                value='on'
              />
              Verdadero
            </label>

            <label class="btn btn-danger" for="<%= "#{yes_no_question.id}_false" %>">
              <input
                type="radio" name="yes_no_question_results[<%= yes_no_question.id %>]"
                id="<%= "#{yes_no_question.id}_false" %>"
                autocomplete="off"
                value='off'
              />
              Falso
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="wrapper mt-5">
  <!-- Page Content  -->
  <div id="content">
    <% @games.each do |game| %>
      <%= render partial: 'game', locals: { game: game } %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="wrapper">
  <div id="content">
    <div class="text-center">
      <p style="font-size: 25px; font-family: Montserrat, Arial, Helvetica, sans-serif; color: #00bfff; text-transform: uppercase; font-weight: bold; line-height: 24px;">
        <%= @game.title %>
      </p>

      <h6>Contesta correctamente las siguientes <%= @game.yes_no_questions.count %> preguntas.</h6>
    </div>

    <%= form_with(url: process_user_input_games_path, method: 'post') do %>
      <input type='hidden' name="id" value='<%= @game.id %>' />
      <div class="d-flex justify-content-center">
        <div class="row">
          <% @game.yes_no_questions.each do |yes_no_question| %>
            <%= render partial: 'yes_no_question', locals: { yes_no_question: yes_no_question, results: @results } %>
          <% end %>
        </div>
      </div>

      <div class='text-center mt-4'>
        <%= submit_tag('Calificar', class: 'btn-success btn') %>
      </div>
    <% end %>

  </div>
</div>