config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources 'provider_sales' do
    get 'find_coupon', on: :collection
    post 'apply_coupon', on: :collection
  end

  resources 'companies'
  resources 'businesses'
  devise_for 'users', controllers: { registrations: 'registrations' }

  root to: "home#index"

  resources 'dashboard' do
    get 'extend_profile_1', on: :collection
    patch 'update_profile', on: :collection
    get 'available_coupons', on: :collection
    post 'obtain_coupon', on: :collection
    get 'coupons_wallet', on: :collection
  end

  resources 'games', only: ['index', 'show', 'evaluate'] do
    post 'process_user_input', on: :collection
  end

  get 'user_root' => 'dashboard#index', as: 'user_root'
  get 'dashboard/extend_profile_1' => 'dashboard#extend_profile_1'
  patch 'dashboard/update_profile' => 'dashboard#update_profile'
end

app/models/company.rb
class Company < ApplicationRecord
  # NOTE: records in the database depend on the order of this array (don't
  # change it unless you're going to make the corresponding updates on the database)
  COMPANY_TYPES = [
    :food_and_drinks,
    :home_products,
    :clothe,
    :groceries
  ].freeze

  MEXICO_STATES = {
    "CDMX" => "CDMX",
    "AGS" => "Aguascalientes",
    "BCN" => "Baja California",
    "BCS" => "Baja California Sur",
    "CAM" => "Campeche",
    "CHP" => "Chiapas",
    "CHI" => "Chihuahua",
    "COA" => "Coahuila",
    "COL" => "Colima",
    "DUR" => "Durango",
    "GTO" => "Guanajuato",
    "GRO" => "Guerrero",
    "HGO" => "Hidalgo",
    "JAL" => "Jalisco",
    "MEX" => "M&eacute;xico",
    "MIC" => "Michoac&aacute;n",
    "MOR" => "Morelos",
    "NAY" => "Nayarit",
    "NLE" => "Nuevo Le&oacute;n",
    "OAX" => "Oaxaca",
    "PUE" => "Puebla",
    "QRO" => "Quer&eacute;taro",
    "ROO" => "Quintana Roo",
    "SLP" => "San Luis Potos&iacute;",
    "SIN" => "Sinaloa",
    "SON" => "Sonora",
    "TAB" => "Tabasco",
    "TAM" => "Tamaulipas",
    "TLX" => "Tlaxcala",
    "VER" => "Veracruz",
    "YUC" => "Yucat&aacute;n",
    "ZAC" => "Zacatecas"
  }.freeze

  validates :name, uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :address, :category_id, :offers_physical_products, :offers_digital_products)
    end
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :offers_physical_products %>
    <%= form.check_box :offers_physical_products %>
  </div>

  <div class="field">
    <%= form.label :offers_digital_products %>
    <%= form.check_box :offers_digital_products %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Category</th>
      <th>Offers physical products</th>
      <th>Offers digital products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.address %></td>
        <td><%= company.category_id %></td>
        <td><%= company.offers_physical_products %></td>
        <td><%= company.offers_digital_products %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Category:</strong>
  <%= @company.category_id %>
</p>

<p>
  <strong>Offers physical products:</strong>
  <%= @company.offers_physical_products %>
</p>

<p>
  <strong>Offers digital products:</strong>
  <%= @company.offers_digital_products %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>