config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources 'provider_sales' do
    get 'find_coupon', on: :collection
    post 'apply_coupon', on: :collection
  end

  resources 'companies'
  resources 'businesses'
  devise_for 'users', controllers: { registrations: 'registrations' }

  root to: "home#index"

  resources 'dashboard' do
    get 'extend_profile_1', on: :collection
    patch 'update_profile', on: :collection
    get 'available_coupons', on: :collection
    post 'obtain_coupon', on: :collection
    get 'coupons_wallet', on: :collection
  end

  resources 'games', only: ['index', 'show', 'evaluate'] do
    post 'process_user_input', on: :collection
  end

  get 'user_root' => 'dashboard#index', as: 'user_root'
  get 'dashboard/extend_profile_1' => 'dashboard#extend_profile_1'
  patch 'dashboard/update_profile' => 'dashboard#update_profile'
end

app/models/provider_sale.rb
# TODO: rename to `provider_sale`
class ProviderSale < ApplicationRecord
  # NOTE: records in the Database depend on the order of `DISCOUNT_TYPES`
  DISCOUNT_TYPES = %w[
    percentage
    money_amount
  ];

  has_one_attached :reference_image
  # has_one :consumer_coupon, foreign_key: 'provider_coupon_id'
end

app/controllers/provider_sales_controller.rb
class ProviderSalesController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!

  def index
    @coupons = ProviderCouponsDecorator
      .new(ProviderSale.where(provider_id: current_user.id))
      .decorate
  end

  def new
  end

  def edit
    @provider_sale.discount_amount = helpers.currency_db_to_ui_format(@provider_sale.discount_amount)
    @provider_sale.product_price = helpers.currency_db_to_ui_format(@provider_sale.product_price)
  end

  def create
    @provider_sale = ProviderSale.new(
      provider_sale_params.merge(
        discount_amount: helpers.currency_ui_to_db_format(params[:provider_sale][:discount_amount]),
        product_price: helpers.currency_ui_to_db_format(params[:provider_sale][:product_price])
      )
    )

    respond_to do |format|
      if @provider_sale.save
        format.html { redirect_to edit_provider_sale_path(@provider_sale), notice: 'Cupón creado.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    params = provider_sale_params.merge(
      discount_amount: helpers.currency_ui_to_db_format(provider_sale_params[:discount_amount]),
      product_price: helpers.currency_ui_to_db_format(provider_sale_params[:product_price])
    )

    respond_to do |format|
      if @provider_sale.update(params)
        format.html { redirect_to provider_sales_path, notice: 'Cupón actualizado.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @provider_sale.destroy
    respond_to do |format|
      format.html { redirect_to provider_sales_url, notice: 'Provider sale was successfully destroyed.' }
    end
  end

  def find_coupon; end

  def apply_coupon
    @consumer_coupon = ConsumerCoupon
      .where(
        provider_coupon_id: ProviderSale
          .where(provider_id: current_user.id)
          .pluck(:id)
      )
      .where('coupon_applied IS NOT true')
      .where(code: params[:coupon_code])
      .first

    unless @consumer_coupon
      flash[:alert] = 'No se encontró ningún cupon activo con ese código. Por favor verifica el código.'
      return redirect_to action: :find_coupon
    end

    if @consumer_coupon.provider_coupon.available_stock < 1
      flash[:alert] = 'Hay un problema de stock con el cupón.'
      return redirect_to action: :find_coupon
    end

    @consumer_coupon.update_attributes!(coupon_applied: true)
    flash[:notice] = 'El cupón ha sido aplicado!'

    redirect_to action: :find_coupon
  end

  private
    def provider_sale_params
      params
        .require(:provider_sale)
        .permit(:provider_id, :title, :description, :product_price, :discount_type, :discount_amount, :required_credits, :available_stock, :reference_image)
    end
end

app/helpers/provider_sales_helper.rb
module ProviderSalesHelper
  def discount_types_for_selector
    ProviderSale::DISCOUNT_TYPES
      .length
      .times
      .map do |i|
        [I18n.t("discount_types.#{ProviderSale::DISCOUNT_TYPES[i]}"), i]
      end
  end

  def discount_to_ui(provider_sale)
    ProviderSale::DISCOUNT_TYPES[provider_sale['discount_type']] == 'percentage' ?
      "#{currency_db_to_ui_format(provider_sale['discount_amount'])}%" :
      "$#{currency_db_to_ui_format(provider_sale['discount_amount'])}"
  end
end

app/views/provider_sales/_coupon_card.html.erb
<% modal_obtain_cupon_id = "modal-obtain-coupon-#{coupon['id']}" %>

<div class="col align-self-center coupon_card">
  <div class="d-flex justify-content-center">
    <div class="card mt-4" style="width: 20rem;">
      <img
        class="card-img-top"
        src='<%= coupon['reference_image'].try(:service_url) %>'
        alt="Card image cap"
      />
      <div class="card-body">
        <div class="coupon-title mt-3">
          <%= coupon['title'] %>
        </div>

        <p class='discount'>
          <%= discount_to_ui(coupon) %> de Descuento
        </p>

        <hr style="margin-top: 0px;" />

        <% if coupon['type'] == 'consumer_coupon' %>
          <div class='stats'>
            <% if coupon['coupon_applied'] %>
              Código: <del><%= coupon['code'] %></del> (cupón aplicado)
            <% else %>
              Código: <%= coupon['code'] %>
            <% end %>
          </div>
        <% else %>
          <div class='stats'>
            <span>
              <% if coupon['type'] == 'provider_coupon' && render_style == 'for_consumer' %>
                <img src='/images/coins.png' width='20px' />
                <%= coupon['required_credits'] %>
                Puntos Requeridos
              <% end %>

              <% if coupon['type'] == 'provider_coupon' && render_style == 'for_provider' %>
                <%= coupon['required_credits'] %>
                Puntos •
                <%= coupon['available_stock'] %>
                Cupones
              <% end %>
            <span>
          </div>
        <% end %>

        <hr />

        <p class='description'>
          <%= coupon['description'] %>
        </p>
      </div>

      <% if coupon['type'] == 'provider_coupon' && render_style == 'for_consumer' %>
        <div class="button-canjear">
          <a
            data-toggle='modal'
            data-target='#<%= modal_obtain_cupon_id %>'
            class='btn btn-success float-right'
            href='#'
          >
            Obtener
          </a>
        </div>
      <% end %>

      <% if coupon['type'] == 'provider_coupon' && render_style == 'for_provider' %>
        <div class="button-canjear">
          <%= link_to edit_provider_sale_path(id: coupon['id']), class: 'btn btn-success float-right' do %>
            <i class='fa fa-pencil'></i>
            Editar
          <% end %>
          <%= link_to 'Borrar', coupon, class: 'btn btn-default-no-background', method: :delete, data: { confirm: 'Por favor confirma.' } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id='<%= modal_obtain_cupon_id %>' class='modal' tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content text-center">
      <div class="modal-header">
        Obtener cupón
      </div>

      <div class="content">
        <div class="row text-left">
          <div class="col" style='font-size: 15px'>
            Estás apunto de obtener este cupón.
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <div class='col text-right'>
          <a href='#' class='btn btn-default-no-background' data-dismiss='modal'>Salir</a>

          <%= link_to 'Obtener', obtain_coupon_dashboard_index_path(coupon_id: coupon['id']), class: 'btn btn-success float-right', method: :post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/provider_sales/_form.html.erb
<%= form_with(model: provider_sale, local: true) do |form| %>
  <% if provider_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provider_sale.errors.count, "error") %> prohibited this provider_sale from being saved:</h2>

      <ul>
        <% provider_sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :provider_id, value: current_user.id %>

  <div class="form-group">
    <%= form.text_field :title, placeholder: 'Título', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, placeholder: 'Descripción', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.text_field :discount_amount, placeholder: 'Descuento', step: '1', min: '1', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.select(:discount_type, discount_types_for_selector, { prompt: 'Selecciona Tipo de Descuento', required: true }, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= form.number_field :product_price, placeholder: 'Precio del Producto', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.number_field :required_credits, type: 'number', class: 'form-control', placeholder: 'Puntos Requeridos', min: '1', step: '1' %>
  </div>

  <div class="form-group">
    <%= form.number_field :available_stock, type: 'number', class: 'form-control', placeholder: 'No. de Cupones Disponibles', min: '1', step: '1' %>
  </div>

  <div class='form-group custom-file'>
    <%= form.file_field :reference_image, class: 'custom-file-input', id: 'reference-image-input' %>
    <label class="custom-file-label" for="customFile">Imagen del producto</label>
  </div>

  <br />
  <br />
  <div class='text-center'>
    <img id='reference-image-thumbnail' src='<%= provider_sale.reference_image.try(:service_url) %>' class='img-thumbnail dashed-border' style='max-height: 300px; max-width: 300px'>
  </div>

  <br />
  <br />
  <div class="actions">
    <%= form.submit(perform_operation_label(provider_sale.id, 'Actualizar cupón', 'Crear cupón'), class: 'btn btn-success float-right') %>
  </div>
<% end %>


<% content_for :footer do %>
<script>
  document.getElementById('reference-image-input').onchange = function() {
    var $thumbnail = document.getElementById('reference-image-thumbnail');
    var fileSrc = (window.URL ? URL : webkitURL).createObjectURL(this.files[0])

    $thumbnail.setAttribute('src', fileSrc);
  }
</script>
<% end %>

app/views/provider_sales/edit.html.erb
<div class='container'>
  <br/ >
  <br />
  <h2>Editar cupón</h2>

  <%= render 'form', provider_sale: @provider_sale %>
  <%= link_to 'Regresar', provider_sales_path, class: 'btn btn-default' %>
  <br />
  <br />
</div>

app/views/provider_sales/find_coupon.html.erb
<div class='container'>
  <br/ >
  <br />
  <h2>Aplicar cupón</h2>

  <%= form_tag(apply_coupon_provider_sales_path) do %>
    <div class="form-group">
      <%= text_field_tag :coupon_code, nil, placeholder: 'Código del cupon', class: 'form-control' %>
    </div>
    <br />

    <%= submit_tag 'Aplicar', class: 'btn btn-success' %>
  <% end %>

  <br />
  <br />
</div>

app/views/provider_sales/index.html.erb
<div class="container" id='provider-sales-index'>
  <div class="row justify-content-center mt-1">
    <p id="notice"><%= notice %></p>
    <% @coupons.each do |coupon| %>
      <%= render partial: 'coupon_card', locals: { coupon: coupon, render_style: 'for_provider' } %>
    <% end %>

    <%= link_to new_provider_sale_path, class: 'btn btn-primary btn-yellow mt-5' do %>
      <i class='fa fa-plus'></i>
      Nuevo cupón
    <% end %>
  </div>
</div>

app/views/provider_sales/new.html.erb
<div class='container'>
  <br/ >
  <br />
  <h2>Nuevo cupón</h2>

  <%= render 'form', provider_sale: @provider_sale %>
  <%= link_to 'Regresar', provider_sales_path, class: 'btn btn-default' %>
  <br />
  <br />
</div>

app/views/provider_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @provider_sale.provider_id %>
</p>

<p>
  <strong>Product price:</strong>
  <%= @provider_sale.product_price %>
</p>

<p>
  <strong>Required credits:</strong>
  <%= @provider_sale.required_credits %>
</p>

<p>
  <strong>Available stock:</strong>
  <%= @provider_sale.available_stock %>
</p>

<%= image_tag @provider_sale.reference_image, width: 50, height: 50 %>

<%= link_to 'Edit', edit_provider_sale_path(@provider_sale) %> |
<%= link_to 'Back', provider_sales_path %>